name: ProgramCode Code Convention (Python)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint_python_code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Super-Linter for Python
        uses: github/super-linter@v6
        env:
          VALIDATE_PYTHON: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
